package main

import (
	"bufio"
	"crypto/tls"
	"embed"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	emailpkg "github.com/yusufkaraaslan/play-more/internal/email"
	"github.com/yusufkaraaslan/play-more/internal/middleware"
	"github.com/yusufkaraaslan/play-more/internal/server"
	"github.com/yusufkaraaslan/play-more/internal/storage"
	"golang.org/x/crypto/acme/autocert"
)

//go:embed all:frontend
var frontendFS embed.FS

// loadEnvFile reads a .env file and sets environment variables (does not override existing ones).
func loadEnvFile(path string) {
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		// Remove surrounding quotes
		if len(val) >= 2 && ((val[0] == '"' && val[len(val)-1] == '"') || (val[0] == '\'' && val[len(val)-1] == '\'')) {
			val = val[1 : len(val)-1]
		}
		if os.Getenv(key) == "" {
			os.Setenv(key, val)
		}
	}
}

func runSetup() {
	reader := bufio.NewReader(os.Stdin)
	ask := func(prompt, def string) string {
		if def != "" {
			fmt.Printf("%s [%s]: ", prompt, def)
		} else {
			fmt.Printf("%s: ", prompt)
		}
		line, _ := reader.ReadString('\n')
		line = strings.TrimSpace(line)
		if line == "" {
			return def
		}
		return line
	}
	askYN := func(prompt string, def bool) bool {
		d := "n"
		if def {
			d = "y"
		}
		ans := strings.ToLower(ask(prompt+" (y/n)", d))
		return ans == "y" || ans == "yes"
	}

	fmt.Println("╔══════════════════════════════════════╗")
	fmt.Println("║       PlayMore Production Setup      ║")
	fmt.Println("╚══════════════════════════════════════╝")
	fmt.Println()

	var lines []string

	// Basic
	port := ask("Server port", "8080")
	lines = append(lines, "PLAYMORE_PORT="+port)

	dataDir := ask("Data directory", "data")
	lines = append(lines, "PLAYMORE_DATA="+dataDir)

	baseURL := ask("Public URL (e.g. https://playmore.example.com)", "")
	if baseURL != "" {
		lines = append(lines, "PLAYMORE_BASE_URL="+baseURL)
	}

	// HTTPS
	fmt.Println()
	fmt.Println("── HTTPS ──")
	fmt.Println("  1) Auto (Let's Encrypt — needs ports 80+443 open)")
	fmt.Println("  2) Manual (provide cert+key files)")
	fmt.Println("  3) None (use reverse proxy like Caddy/nginx)")
	tlsChoice := ask("HTTPS mode", "3")

	switch tlsChoice {
	case "1":
		domain := ask("Domain name", "")
		if domain != "" {
			lines = append(lines, "PLAYMORE_AUTO_TLS=true")
			lines = append(lines, "PLAYMORE_DOMAIN="+domain)
			if baseURL == "" {
				lines = append(lines, "PLAYMORE_BASE_URL=https://"+domain)
			}
		}
	case "2":
		cert := ask("TLS certificate file path", "")
		key := ask("TLS private key file path", "")
		if cert != "" && key != "" {
			lines = append(lines, "PLAYMORE_TLS_CERT="+cert)
			lines = append(lines, "PLAYMORE_TLS_KEY="+key)
		}
	}

	// Email
	fmt.Println()
	if askYN("Enable email (verification + password reset)?", false) {
		smtpHost := ask("SMTP host", "smtp.gmail.com")
		smtpPort := ask("SMTP port", "587")
		smtpUser := ask("SMTP username", "")
		smtpPass := ask("SMTP password", "")
		smtpFrom := ask("From address", smtpUser)
		lines = append(lines, "PLAYMORE_SMTP_HOST="+smtpHost)
		lines = append(lines, "PLAYMORE_SMTP_PORT="+smtpPort)
		lines = append(lines, "PLAYMORE_SMTP_USER="+smtpUser)
		lines = append(lines, "PLAYMORE_SMTP_PASS="+smtpPass)
		lines = append(lines, "PLAYMORE_SMTP_FROM="+smtpFrom)
	}

	// Analytics
	fmt.Println()
	gc := ask("GoatCounter URL (leave empty to skip)", "")
	if gc != "" {
		lines = append(lines, "PLAYMORE_GOATCOUNTER="+gc)
	}

	// Write .env
	envContent := "# PlayMore configuration — generated by ./playmore setup\n" + strings.Join(lines, "\n") + "\n"
	envPath := ".env"
	if err := os.WriteFile(envPath, []byte(envContent), 0600); err != nil {
		log.Fatal("Failed to write .env:", err)
	}

	fmt.Println()
	fmt.Println("✓ Saved to .env")
	fmt.Println()
	fmt.Println("Now just run:")
	fmt.Println("  ./playmore")
	fmt.Println()
}

func main() {
	// Handle "setup" subcommand before flag parsing
	if len(os.Args) > 1 && os.Args[1] == "setup" {
		runSetup()
		return
	}

	// Load .env file (doesn't override existing env vars)
	loadEnvFile(".env")

	// Default to release mode unless GIN_MODE is explicitly set
	if os.Getenv("GIN_MODE") == "" {
		gin.SetMode(gin.ReleaseMode)
	}

	port := flag.Int("port", 8080, "server port")
	dataDir := flag.String("data", "data", "data directory path")
	goatcounter := flag.String("goatcounter", "", "GoatCounter URL (e.g. https://mysite.goatcounter.com)")
	tlsCert := flag.String("tls-cert", "", "path to TLS certificate file")
	tlsKey := flag.String("tls-key", "", "path to TLS private key file")
	autoTLS := flag.Bool("auto-tls", false, "enable automatic TLS via Let's Encrypt")
	domain := flag.String("domain", "", "domain name for auto-TLS certificate (required with --auto-tls)")
	smtpHost := flag.String("smtp-host", "", "SMTP server hostname")
	smtpPort := flag.Int("smtp-port", 587, "SMTP server port")
	smtpUser := flag.String("smtp-user", "", "SMTP username")
	smtpPass := flag.String("smtp-pass", "", "SMTP password")
	smtpFrom := flag.String("smtp-from", "", "From address for emails")
	baseURL := flag.String("base-url", "", "Public base URL (e.g. https://playmore.example.com)")
	gamesDomain := flag.String("games-domain", "", "Optional separate domain for game files (e.g. games.example.com) — strongest isolation against malicious uploaded games")
	trustedProxies := flag.String("trusted-proxies", "", "Comma-separated list of trusted proxy CIDRs (e.g. '127.0.0.1/32,10.0.0.0/8'). Empty = trust no proxy headers.")
	forceSecure := flag.Bool("behind-tls-proxy", false, "Always set Secure flag on cookies (use when behind a TLS-terminating reverse proxy)")
	flag.Parse()

	// Environment variables as fallback (flags take priority)
	if !isFlagSet("port") {
		if v := os.Getenv("PLAYMORE_PORT"); v != "" {
			if p, err := strconv.Atoi(v); err == nil {
				*port = p
			}
		}
	}
	if !isFlagSet("data") {
		if v := os.Getenv("PLAYMORE_DATA"); v != "" {
			*dataDir = v
		}
	}
	if !isFlagSet("goatcounter") {
		if v := os.Getenv("PLAYMORE_GOATCOUNTER"); v != "" {
			*goatcounter = v
		}
	}
	if !isFlagSet("tls-cert") {
		if v := os.Getenv("PLAYMORE_TLS_CERT"); v != "" {
			*tlsCert = v
		}
	}
	if !isFlagSet("tls-key") {
		if v := os.Getenv("PLAYMORE_TLS_KEY"); v != "" {
			*tlsKey = v
		}
	}
	if !isFlagSet("auto-tls") {
		if v := os.Getenv("PLAYMORE_AUTO_TLS"); v == "true" || v == "1" {
			*autoTLS = true
		}
	}
	if !isFlagSet("domain") {
		if v := os.Getenv("PLAYMORE_DOMAIN"); v != "" {
			*domain = v
		}
	}

	if !isFlagSet("smtp-host") {
		if v := os.Getenv("PLAYMORE_SMTP_HOST"); v != "" { *smtpHost = v }
	}
	if !isFlagSet("smtp-port") {
		if v := os.Getenv("PLAYMORE_SMTP_PORT"); v != "" {
			if p, err := strconv.Atoi(v); err == nil { *smtpPort = p }
		}
	}
	if !isFlagSet("smtp-user") {
		if v := os.Getenv("PLAYMORE_SMTP_USER"); v != "" { *smtpUser = v }
	}
	if !isFlagSet("smtp-pass") {
		if v := os.Getenv("PLAYMORE_SMTP_PASS"); v != "" { *smtpPass = v }
	}
	if !isFlagSet("smtp-from") {
		if v := os.Getenv("PLAYMORE_SMTP_FROM"); v != "" { *smtpFrom = v }
	}
	if !isFlagSet("base-url") {
		if v := os.Getenv("PLAYMORE_BASE_URL"); v != "" { *baseURL = v }
	}
	if !isFlagSet("games-domain") {
		if v := os.Getenv("PLAYMORE_GAMES_DOMAIN"); v != "" { *gamesDomain = v }
	}
	if !isFlagSet("trusted-proxies") {
		if v := os.Getenv("PLAYMORE_TRUSTED_PROXIES"); v != "" { *trustedProxies = v }
	}
	if !isFlagSet("behind-tls-proxy") {
		if v := os.Getenv("PLAYMORE_BEHIND_TLS_PROXY"); v == "true" || v == "1" { *forceSecure = true }
	}
	middleware.ForceSecureCookies = *forceSecure

	// Validate TLS options
	if (*tlsCert == "") != (*tlsKey == "") {
		log.Fatal("Both --tls-cert/PLAYMORE_TLS_CERT and --tls-key/PLAYMORE_TLS_KEY must be provided together")
	}
	if *autoTLS && *domain == "" {
		log.Fatal("--domain/PLAYMORE_DOMAIN is required when using --auto-tls")
	}
	if *autoTLS && *tlsCert != "" {
		log.Fatal("Cannot use --auto-tls together with --tls-cert/--tls-key")
	}

	// Initialize storage
	if err := storage.InitDB(*dataDir); err != nil {
		log.Fatal("Failed to initialize database:", err)
	}
	if err := storage.InitFileStorage(*dataDir); err != nil {
		log.Fatal("Failed to initialize file storage:", err)
	}

	// Configure email
	emailpkg.Host = *smtpHost
	emailpkg.Port = *smtpPort
	emailpkg.User = *smtpUser
	emailpkg.Pass = *smtpPass
	emailpkg.From = *smtpFrom
	emailpkg.BaseURL = *baseURL

	// SMTP health check (non-fatal — email is optional)
	if emailpkg.Configured() {
		if err := emailpkg.HealthCheck(); err != nil {
			fmt.Printf("⚠  SMTP health check failed (%s:%d): %v\n", emailpkg.Host, emailpkg.Port, err)
			if emailpkg.IsLocalBridge() {
				// Try auto-starting protonmail-bridge on Linux
				if tryStartLocalBridge() {
					// Wait briefly for service to come up
					for i := 0; i < 10; i++ {
						time.Sleep(500 * time.Millisecond)
						if emailpkg.HealthCheck() == nil {
							fmt.Printf("✓  SMTP reachable after starting local bridge\n")
							goto smtpOK
						}
					}
				}
				fmt.Println("   Local bridge not reachable. Start it manually:")
				fmt.Println("   sudo systemctl start protonmail-bridge")
				fmt.Println("   (or see docs/SETUP_PROTONMAIL_BRIDGE.md)")
			smtpOK:
			} else {
				fmt.Println("   Email verification/reset will fail until SMTP is reachable.")
			}
		} else {
			fmt.Printf("✓  SMTP reachable at %s:%d\n", emailpkg.Host, emailpkg.Port)
		}
	} else {
		fmt.Println("ℹ  SMTP not configured — email verification and password reset disabled")
	}

	middleware.StartRateLimitCleanup()
	middleware.StartAnalyticsWriter()

	scheme := "http"
	if *tlsCert != "" || *autoTLS {
		scheme = "https"
	}
	fmt.Printf("PlayMore server starting on %s://localhost:%d\n", scheme, *port)
	fmt.Printf("Data directory: %s\n", *dataDir)
	if *goatcounter != "" {
		fmt.Printf("GoatCounter: %s\n", *goatcounter)
	}
	if *autoTLS {
		fmt.Printf("Auto-TLS: enabled for %s\n", *domain)
	}

	r := server.New(frontendFS, *goatcounter, *gamesDomain, *trustedProxies)
	addr := fmt.Sprintf(":%d", *port)
	if *autoTLS {
		certDir := filepath.Join(*dataDir, "certs")
		m := &autocert.Manager{
			Cache:      autocert.DirCache(certDir),
			Prompt:     autocert.AcceptTOS,
			HostPolicy: autocert.HostWhitelist(*domain),
		}
		s := &http.Server{
			Addr:    ":443",
			Handler: r.Handler(),
			TLSConfig: &tls.Config{
				GetCertificate: m.GetCertificate,
			},
		}
		// HTTP challenge server + redirect on port 80
		go func() {
			h := m.HTTPHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				target := "https://" + r.Host + r.URL.Path
				if len(r.URL.RawQuery) > 0 {
					target += "?" + r.URL.RawQuery
				}
				http.Redirect(w, r, target, http.StatusMovedPermanently)
			}))
			log.Fatal(http.ListenAndServe(":80", h))
		}()
		fmt.Printf("Listening on :443 (auto-TLS) and :80 (redirect)\n")
		if err := s.ListenAndServeTLS("", ""); err != nil {
			log.Fatal("Server failed:", err)
		}
	} else if *tlsCert != "" {
		if err := r.RunTLS(addr, *tlsCert, *tlsKey); err != nil {
			log.Fatal("Server failed:", err)
		}
	} else {
		if err := r.Run(addr); err != nil {
			log.Fatal("Server failed:", err)
		}
	}
}

// tryStartLocalBridge attempts to start protonmail-bridge via systemctl.
// Returns true if a start command was issued successfully.
func tryStartLocalBridge() bool {
	// Only try on Linux with systemd
	if _, err := os.Stat("/run/systemd/system"); err != nil {
		return false
	}
	// Try common service names (protonmail-bridge or proton-bridge)
	for _, svc := range []string{"protonmail-bridge", "proton-bridge"} {
		cmd := exec.Command("systemctl", "is-active", "--quiet", svc)
		if err := cmd.Run(); err == nil {
			// Already active
			return true
		}
		// Try starting
		cmd = exec.Command("systemctl", "start", svc)
		if err := cmd.Run(); err == nil {
			fmt.Printf("→  Started %s via systemctl\n", svc)
			return true
		}
		// Try user-level service
		cmd = exec.Command("systemctl", "--user", "start", svc)
		if err := cmd.Run(); err == nil {
			fmt.Printf("→  Started user service %s via systemctl\n", svc)
			return true
		}
	}
	return false
}

func isFlagSet(name string) bool {
	found := false
	flag.Visit(func(f *flag.Flag) {
		if f.Name == name {
			found = true
		}
	})
	return found
}
