name: Deploy v1 to GitHub Pages

on:
  push:
    branches: [main]
    paths: [v1/**]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6f4625a3d97c5 # v3.0.1
        with:
          path: v1
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed371e51d3573963d3c # v4.0.5
